# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RandomDrawUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(388, 111)
        self.name_edit = QtWidgets.QTextEdit(Form)
        self.name_edit.setGeometry(QtCore.QRect(40, 30, 111, 51))
        self.name_edit.setObjectName("name_edit")
        self.order_edit = QtWidgets.QTextEdit(Form)
        self.order_edit.setGeometry(QtCore.QRect(160, 30, 71, 51))
        self.order_edit.setObjectName("order_edit")
        self.start_button = QtWidgets.QPushButton(Form)
        self.start_button.setGeometry(QtCore.QRect(240, 30, 51, 51))
        self.start_button.setObjectName("start_button")
        self.stop_button = QtWidgets.QPushButton(Form)
        self.stop_button.setGeometry(QtCore.QRect(300, 30, 51, 51))
        self.stop_button.setObjectName("stop_button")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.start_button.setText(_translate("Form", "开始"))
        self.stop_button.setText(_translate("Form", "结束"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
